OPSEXP-1853: migrate search-service
Alfresco/alfresco-helm-charts pull request #15
Opened 2023-03-01 18:37 UTC by alxgomz

Ref: OPSEXP-1853

2023-03-02 10:33 UTC, gionn requested changes
gitignore also .DS_Store and check that you actually commited a tgz

2023-03-02 10:33 UTC, gionn commented on charts/alfresco-search-service/Chart.yaml
> +    condition: alfresco-insight-zeppelin.enabled
I assumed we were moving it outside of search chart, why not?

2023-03-02 10:33 UTC, gionn commented on .gitignore
> +/charts/*/charts/*.tgz
```suggestion
*.tgz
```

2023-03-03 11:48 UTC, slohe1 approved these changes

2023-03-06 10:25 UTC, upandey123 approved these changes

2023-03-06 13:22 UTC, merged