OPSEXP-2296 Review and align chart alfresco-connector-msteams with newer principals
Alfresco/alfresco-helm-charts pull request #159
Opened 2023-12-07 09:51 UTC by slohe1

2023-12-08 10:25 UTC, alxgomz requested changes
The following things are mising (please see the JIRA):
* chart.serviceAccount template
* chart offers the ability to provide configuration of other components of the platform through configmap

2023-12-08 10:25 UTC, alxgomz commented on charts/alfresco-connector-msteams/templates/deployment-connector-msteams.yaml
> +    {{- include "alfresco-common.component-pod-security-context" .Values | indent 4 }}
please add missing unit tests

2023-12-08 10:25 UTC, alxgomz commented on charts/alfresco-connector-msteams/templates/deployment-connector-msteams.yaml
> +      {{- include "alfresco-common.imagePullSecrets" . | indent 6 }}
please add missing unit tests

2023-12-08 10:25 UTC, alxgomz commented on charts/alfresco-connector-msteams/templates/deployment-connector-msteams.yaml
> +          {{- include "alfresco-common.component-security-context" .Values | indent 8 }}
please add missing unit tests

2023-12-21 10:48 UTC, gionn reviewed
to fix the tests add some random value to the required values in ci/default-values.yaml

2023-12-21 10:48 UTC, gionn commented on charts/alfresco-connector-msteams/templates/secret-msteams.yaml
> +  MICROSOFT_APP_ID: {{ .Values.microsoft.app.id  }}
```suggestion
  MICROSOFT_APP_ID: {{ .Values.microsoft.app.id }}
```

2024-01-03 08:32 UTC, gionn commented on charts/alfresco-connector-msteams/Chart.yaml
> +version: 0.2.1-alpha.0
you are adding new features which are retrocompat, so it's a minor version bump, not a patch

2024-01-03 08:32 UTC, gionn commented on charts/alfresco-connector-msteams/templates/secret-msteams.yaml
> +  name: {{ template "alfresco-connector-msteams.fullname" $secretCtx }}
it's better to have a named helper so you avoid this copy-pasta in multiple places, like I did [here](https://github.com/Alfresco/alfresco-helm-charts/pull/175/files#diff-cead3e4fd48780ae4d8f8e2cc4fb668b1e73bc40a836a1a143c13170e36b98fa)

2024-01-03 08:32 UTC, gionn commented on charts/alfresco-connector-msteams/tests/configmap_test.yaml
> +- configmap-repository.yaml
I prefer we keep unrelated resources in separated test suite files, e.g. config-connector-msteams_test.yaml and configmap-repository_test.yaml

in that way you can also avoid having to repeat `template` in every test

2024-01-03 13:17 UTC, gionn requested changes

2024-01-03 13:17 UTC, gionn commented on charts/alfresco-connector-msteams/Chart.yaml
> +version: 0.2.1
```suggestion
version: 0.3.0-alpha.0
```

2024-01-04 08:32 UTC, gionn approved these changes

2024-01-04 08:49 UTC, merged