OPSEXP-2295 Review and align chart alfresco-connector-ms365 with newer principals
Alfresco/alfresco-helm-charts pull request #180
Opened 2024-01-08 08:17 UTC by slohe1

2024-01-09 08:22 UTC, gionn requested changes

2024-01-09 08:22 UTC, gionn commented on charts/alfresco-connector-ms365/templates/deployment-connector-ms365.yaml
> +      {{- end }}
move it to the bottom of the deployment and add affinity/tolerations like we did in the recent PRs

2024-01-09 08:22 UTC, gionn commented on charts/alfresco-connector-ms365/templates/deployment-connector-ms365.yaml
>            preferredDuringSchedulingIgnoredDuringExecution:
this need to be moved to values (as part of the previous review comment)

2024-01-09 14:38 UTC, gionn requested changes

2024-01-09 14:38 UTC, gionn commented on charts/alfresco-connector-ms365/templates/_helpers-env.tpl
> +{{- define "alfresco-connector-ms365.repo-ms365.env" -}}
remove `repo-ms365` from the name or move L17-24 back to deployment template because those are not really related to repository configuration

2024-01-09 14:38 UTC, gionn commented on charts/alfresco-connector-ms365/README.md.gotmpl
> +{{ template "chart.valuesSection" . }}
```suggestion
{{ template "chart.valuesSection" . }}

```

strange that pre-commit is not complaining on this

2024-01-10 15:00 UTC, alxgomz approved these changes

2024-01-11 09:17 UTC, gionn approved these changes

2024-01-11 09:18 UTC, merged