OPSEXP-1861 Add alfresco transform service chart
Alfresco/alfresco-helm-charts pull request #29
Opened 2023-04-05 13:37 UTC by gionn

Ref: OPSEXP-1861

- [x] ATS
- [x] unit tests

2023-04-24 14:16 UTC, alxgomz requested changes

2023-04-24 14:16 UTC, alxgomz commented on charts/alfresco-transform-service/templates/config-libreoffice.yaml
> +  maxTransformSeconds: "{{ .Values.libreoffice.livenessProbe.maxTransformSeconds }}"
really want strings?

2023-04-24 14:16 UTC, alxgomz commented on charts/alfresco-transform-service/values.yaml
> +    repository: alfresco/alfresco-pdf-renderer
I think we should point to quay by default but we can tackle as pat of a different ticket if you prefer

2023-04-24 14:16 UTC, alxgomz commented on charts/alfresco-transform-service/values.yaml
> +messageBroker: &acs_messageBroker
this anchor seems unused now.

2023-04-24 14:16 UTC, alxgomz commented on charts/alfresco-transform-service/values.yaml
> +  secretName: &acs_messageBroker_secretName acs-alfresco-cs-brokersecret
this anchor seems unused now.

2023-05-03 15:05 UTC, gionn commented on charts/alfresco-transform-service/values.yaml
> +  edition: "Enterprise"
move to global or another another properly named value?

2023-05-03 15:35 UTC, gionn commented on charts/alfresco-transform-service/templates/config-imagemagick.yaml
> +  maxTransformSeconds: "{{ .Values.imagemagick.livenessProbe.maxTransformSeconds }}"
values needs to be coerced to strings because configmap data doesn't allow anything else

2023-07-03 09:51 UTC, alxgomz commented
Will open a new PR to avoid confusion as I took this one over from Gio

2023-07-03 09:51 UTC, closed without merging