OPSEXP-2991 Change sync service ingress pathType to ImplementationSpecific
Alfresco/alfresco-helm-charts pull request #430
Opened 2024-12-20 14:04 UTC by pmacius

Ref: OPSEXP-2991

2025-01-02 10:56 UTC, gionn requested changes

2025-01-02 10:56 UTC, gionn commented on charts/alfresco-sync-service/README.md
> +| ingress.hosts[0].paths[0].pathType | string | `"ImplementationSpecific"` |  |
is really necessary to keep using this regexp? I remember it's here since forever and I can't understand which a simple `Prefix` & `/syncservice` should not have the same behavior

2025-01-08 09:44 UTC, pmacius commented on charts/alfresco-sync-service/README.md
> +| ingress.hosts[0].paths[0].pathType | string | `"ImplementationSpecific"` |  |
As we discussed ingress is using rewrite target so it is required do have this regex: 
https://kubernetes.github.io/ingress-nginx/examples/rewrite/#rewrite-target

2025-01-08 17:09 UTC, gionn approved these changes

2025-01-08 17:27 UTC, merged