OPSEXP-1861: add transformatin service chart
Alfresco/alfresco-helm-charts pull request #64
Opened 2023-07-03 09:53 UTC by alxgomz

Ref: OPSEXP-1861
This PR aims at producing an initial version of the chart in order to test its integration in acs-deplyment

2023-07-03 13:04 UTC, gionn requested changes

2023-07-03 13:04 UTC, gionn commented on charts/alfresco-transform-service/templates/_helpers-filestore.tpl
deprecated - remove the file

2023-07-03 13:04 UTC, gionn commented on charts/alfresco-transform-service/templates/_helpers-imagemagick.tpl
deprecated - remove the file

2023-07-03 13:04 UTC, gionn commented on charts/alfresco-transform-service/templates/_helpers-libreoffice.tpl
deprecated - remove the file

2023-07-03 13:04 UTC, gionn commented on charts/alfresco-transform-service/templates/_helpers-pdfrenderer.tpl
deprecated - remove the file

2023-07-03 13:04 UTC, gionn commented on charts/alfresco-transform-service/templates/_helpers-tika.tpl
deprecated - remove the file

2023-07-03 13:04 UTC, gionn commented on charts/alfresco-transform-service/templates/_helpers-transform-misc.tpl
deprecated - remove the file

2023-07-03 13:04 UTC, gionn commented on charts/alfresco-transform-service/templates/_helpers-transform-router.tpl
deprecated - remove the file

2023-07-04 08:26 UTC, gionn approved these changes

2023-07-04 08:34 UTC, slohe1 approved these changes

2023-07-04 09:11 UTC, merged