OPSEXP-2116 repository service named template alfresco-connector-ms365
Alfresco/alfresco-helm-charts pull request #71
Opened 2023-07-07 15:07 UTC by slohe1

2023-07-10 07:07 UTC, gionn approved these changes

2023-07-10 07:07 UTC, gionn requested changes

2023-07-10 07:07 UTC, gionn commented on charts/alfresco-connector-ms365/templates/_helpers.tpl
> +{{- define "alfresco-connector-ms365.repository" -}}
you are not using it anywhere

add a test

2023-07-10 14:20 UTC, alxgomz requested changes
the `nameOverride` or `fullnameOberride` for the repo should be set by the parent chart.
I have tried that same approach of using override in subchart and figured out it has several drawback. It creates a lot of nesting, and doesn't play well with external components (where you would have the subchart's component disabled but still leverage the override underneeth it...

I think a better approach is to expect the parent chart to pass the repo URL details in a string (e.g. using the `fullnameOverride`  passed in `alfresco-connector-ms365.repository.host`) and also support reading the repo details from an existing configmap (generated by the parent chart.

2023-07-14 09:49 UTC, gionn approved these changes

2023-07-14 09:49 UTC, gionn commented on charts/alfresco-connector-ms365/values.yaml
> +  existingConfigMap:
```suggestion
  existingConfigMap: null
```

or updatecli will complain later :D

2023-07-14 11:00 UTC, merged