OPSEXP-2188: narrow the usage of existingConfigMap for better integration
Alfresco/alfresco-helm-charts pull request #74
Opened 2023-07-17 13:20 UTC by alxgomz

Ref: OPSEXP-2188

mostly an RFC i particular regarding the structure of the charts values

2023-07-17 13:42 UTC, gionn requested changes

2023-07-17 13:42 UTC, gionn commented on charts/alfresco-share/templates/deployment-share.yaml
> +                  key: {{ .Values.repository.existingConfigMap.keys.port | default "REPO_HOST" }}
```suggestion
                  key: {{ .Values.repository.existingConfigMap.keys.port | default "REPO_PORT" }}
```

2023-07-17 13:42 UTC, gionn commented on charts/alfresco-share/values.yaml
> +      port:
I prefer have the defaults here rather than in the template as fallback

2023-07-18 05:28 UTC, slohe1 approved these changes
LGTM

2023-07-18 13:06 UTC, gionn requested changes

2023-07-18 13:06 UTC, gionn commented on charts/alfresco-sync-service/Chart.lock
> +generated: "2023-07-18T13:01:41.970559642Z"
please rebase or amend&pushforce or add an empty commit - these are untested

we probably need to move to alfresco-build PAT

2023-07-18 13:28 UTC, merged