OPSEXP-2116 Approach change for exsitingConfigMap
Alfresco/alfresco-helm-charts pull request #77
Opened 2023-07-18 13:31 UTC by slohe1

2023-07-19 19:08 UTC, alxgomz requested changes

2023-07-19 19:08 UTC, alxgomz commented on charts/alfresco-connector-ms365/templates/deployment-connector-ms365.yaml
> -            {{- end }}
I don't think you should remove that. You still want to have all other options as per the `.environment` values specified. Only JAVA_OPTS are a special case and treated separately to make sure we include the baseUrl option

2023-07-21 11:00 UTC, gionn requested changes

2023-07-21 11:00 UTC, gionn commented on charts/alfresco-connector-ms365/templates/deployment-connector-ms365.yaml
> +            {{- $repo_url := printf "-Dalfresco.base-url=http://%s:%d" "$REPO_HOST" "$REPO_PORT" }}
```suggestion
            {{- $repo_url := printf "-Dalfresco.base-url=http://%s:%s" "$REPO_HOST" "$REPO_PORT" }}
```

2023-07-21 11:00 UTC, gionn commented on charts/alfresco-connector-ms365/templates/deployment-connector-ms365.yaml
> +            {{- $repo_url := printf "-Dalfresco.base-url=http://%s:%d" "$REPO_HOST" "$REPO_PORT" }}
%d is for decimal

2023-07-21 13:59 UTC, alxgomz requested changes
Please make sure to force push again to remove the updatecli auto commit. We need to change it to a workflow_dispatch only

2023-07-21 13:59 UTC, alxgomz commented on charts/alfresco-connector-ms365/templates/deployment-connector-ms365.yaml
> +            {{- $repo_url := printf "-Dalfresco.base-url=http://%s:%s" "$REPO_HOST" "$REPO_PORT" }}
watch your indentation

2023-07-21 13:59 UTC, alxgomz commented on charts/alfresco-connector-ms365/tests/configmap-connector-ms365_test.yaml
> +  - it: should render custom repo & CSRF config
You're not checking CSRF here. Make sure the name is sensible

2023-07-24 07:32 UTC, alxgomz requested changes
You still have  the changes to thee sync charts which we don't want (IIRC the postgres upgrade requires more changes)
Make sure to force push your branch (assuming you don't have this change on your local env) to get rid of this.

2023-07-24 07:32 UTC, alxgomz commented on charts/alfresco-connector-ms365/templates/deployment-connector-ms365.yaml
> +              value: {{ printf "%s%s" (.Values.environment.JAVA_OPTS | default "") ($repo_url) }}
without a space you may mess up the java command line

```suggestion
              value: {{ printf "%s %s" (.Values.environment.JAVA_OPTS | default "") ($repo_url) }}
```

2023-07-24 11:45 UTC, alxgomz requested changes

2023-07-24 11:45 UTC, alxgomz commented on charts/alfresco-sync-service/Chart.yaml
> +version: 4.3.0
please make it 4.2.1. I would consider this a bugfix

2023-07-25 08:26 UTC, alxgomz approved these changes

2023-07-25 10:13 UTC, gionn approved these changes

2023-07-25 10:14 UTC, merged